<%@ Page Language="C#" AutoEventWireup="true" Inherits="Bitrix.UI.BXPublicPage, Main"  Title="Products" %>

<script runat="server" id="@__bx_pagekeywords">
	public override void SetPageKeywords(System.Collections.Generic.IDictionary<string, string> keywords)
	{
		keywords[@"guga"]=@"";
	}
</script>

<asp:Content ID="Content1" ContentPlaceHolderID="BXContent" runat="server" > 
<bx:IncludeComponent 
	id="catalogue2" 
	runat="server" 
	componentname="bitrix:catalogue" 
	template="goods" 
	IBlockTypeId="" 
	IBlockId="<%$ Options:Bitrix.CorporateSite:CatalogIblockId,int %>" 
	ListSortBy="ID" 
	ListSortOrder="Desc" 
	ShowSubElements="True" 
	ShowAllElementsOnIndex="True" 
	ActiveFilter="Active" 
	ActiveDateFilter="All" 
	ListProperties="-" 
	DetailProperties="SIZE;S_SIZE;ARTNUMBER;MATERIAL;MANUFACTURER" 
	PropertyKeywords="-" 
	PropertyDescription="-" 
	DepthLevel="2" 
	ShowCounters="False" 
	IncludeParentSections="True" 
	AddAdminPanelButtons="False" 
	SetPageTitle="True" 
	RootSectionTitle="Products" 
	ShowTopElements="False" 
	TopElementCount="6" 
	TopSortBy="ID" 
	TopSortOrder="Desc" 
	TopProperties="-" 
	EnableSEF="True" 
	SEFFolder="<%$ Options:Bitrix.CorporateSite:ProductsSEFFolder %>" 
	SectionIdVariable="section_id" 
	ElementIdVariable="element_id" 
	PageIdVariable="page" 
	ShowAllVariable="showall" 
	CommentVariable="comment" 
	CommentOperationVariable="act" 
	CommentPageVariable="page" 
	ElementDetailTemplate="/#SectionId#/item-#ElementId#/" 
	ElementListTemplate="/#SectionId#/" 
	CommonListPageTemplate="/page-#pageId#" 
	CommonListShowAllTemplate="/all" 
	SectionListPageTemplate="/#SectionId#/page-#pageId#" 
	SectionListShowAllTemplate="/#SectionId#/all" 
	ElementDetailCommentReadTemplate="/#SectionId#/item-#ElementId#/comment-#CommentId#/" 
	ElementDetailCommentOperationTemplate="/#SectionId#/item-#ElementId#/comment-#CommentId#/act-#Operation#/" 
	ElementDetailCommentPageTemplate="/#SectionId#/item-#ElementId#/page-#PageID#/" 
	AllowComments="False" 
	CommentsPerPage="5" 
	CommentsForumId="0" 
	CommentAuthorProfileUrlTemplate="" 
	DisplayEmailForGuestComment="True" 
	RequireEmailForGuestComment="True" 
	DisplayCaptchaForGuestComment="True" 
	CommentMaxWordLength="15" 
	PagingAllow="True" 
	PagingMode="direct" 
	PagingTemplate="catalog" 
	PagingShowOne="False" 
	PagingAllowAll="False" 
	PagingRecordsPerPage="4" 
	PagingTitle="Pages:" 
	PagingPosition="bottom" 
	PagingMaxPages="5" 
	PagingMinRecordsInverse="1" 
	CacheMode="None" 
	CacheDuration="30" 
	DisplaySearchResults="True" 
	EnableAjax="False" 
	GenerateMenu="True" 
	GenerateMenuType="left" 
/> 
<br />
</asp:Content>

