<%@ Page Language="C#" AutoEventWireup="true" Inherits="Bitrix.UI.BXPublicPage, Main"  Title="Services" %>

<script runat="server" id="@__bx_pagekeywords">
	public override void SetPageKeywords(System.Collections.Generic.IDictionary<string, string> keywords)
	{
		keywords[@"guga"]=@"";
	}
</script>

<asp:Content ID="Content1" ContentPlaceHolderID="BXContent" runat="server" >
<bx:IncludeComponent 
	id="catalogue1" 
	runat="server" 
	componentname="bitrix:catalogue" 
	template="services" 
	IBlockTypeId="" 
	IBlockId="<%$ Options:Bitrix.CorporateSite:ServicesIblockId,int %>" 
	AddAdminPanelButtons="True" 
	SetPageTitle="True" 
	RootSectionTitle="" 
	GenerateMenu="True" 
	GenerateMenuType="left" 
	AllowComments="False" 
	CommentsPerPage="5" 
	CommentsForumId="0" 
	CommentAuthorProfileUrlTemplate="" 
	DisplayEmailForGuestComment="True" 
	RequireEmailForGuestComment="True" 
	DisplayCaptchaForGuestComment="True" 
	CommentMaxWordLength="15" 
	EnableSEF="True" 
	SEFFolder="<%$ Options:Bitrix.CorporateSite:ServicesSEFFolder %>" 
	SectionIdVariable="section_id" 
	ElementIdVariable="element_id" 
	PageIdVariable="page" 
	ShowAllVariable="showall" 
	CommentVariable="comment" 
	CommentOperationVariable="act" 
	CommentPageVariable="page" 
	ElementDetailTemplate="/item-#ElementId#/" 
	ElementListTemplate="/#SectionId#/" 
	CommonListPageTemplate="/page-#pageId#" 
	CommonListShowAllTemplate="/all" 
	SectionListPageTemplate="/page-#pageId#" 
	SectionListShowAllTemplate="/#SectionId#/all" 
	ElementDetailCommentReadTemplate="/item-#ElementId#/comment-#CommentId#/" 
	ElementDetailCommentOperationTemplate="/item-#ElementId#/comment-#CommentId#/act-#Operation#/" 
	ElementDetailCommentPageTemplate="/item-#ElementId#/page-#PageID#/" 
	EnableAjax="False" 
	DisplaySearchResults="True" 
	ListSortBy="ID" 
	ListSortOrder="Desc" 
	ShowSubElements="True" 
	ShowAllElementsOnIndex="True" 
	ActiveFilter="Active" 
	ActiveDateFilter="All" 
	ListProperties="" 
	DetailProperties="" 
	PropertyKeywords="-" 
	PropertyDescription="-" 
	DepthLevel="2" 
	ShowCounters="False" 
	IncludeParentSections="True" 
	ShowTopElements="False" 
	TopElementCount="6" 
	TopSortBy="ID" 
	TopSortOrder="Desc" 
	TopProperties="" 
	PagingAllow="True" 
	PagingMode="direct" 
	PagingTemplate="catalog" 
	PagingShowOne="False" 
	PagingAllowAll="False" 
	PagingRecordsPerPage="4" 
	PagingTitle="Pages" 
	PagingPosition="both" 
	PagingMaxPages="10" 
	PagingMinRecordsInverse="1" 
	CacheMode="None" 
	CacheDuration="30" 
/> </asp:Content>
