<%@ Page Language="C#" AutoEventWireup="true" Inherits="Bitrix.UI.BXPublicPage, Main" Title="News" %>



<asp:Content ID="Content1" ContentPlaceHolderID="bxcontent" runat="server" > 
<bx:IncludeComponent 
	id="news1" 
	runat="server" 
	componentname="bitrix:news" 
	template="news" 
	IBlockTypeId="" 
	IBlockId="<%$ Options:Bitrix.BankSite:BankNewsIBlockId,int %>" 
	PagingRecordsPerPage="5" 
	SortBy1="ActiveFromDate" 
	SortBy2="ID" 
	SortOrder1="Desc" 
	SortOrder2="Desc" 
	DisplayPanel="False" 
	ShowActiveElements="True" 
	IncludeSubsections="True" 
	UsePermissions="False" 
	GroupPermissions="" 
	GenerateMenu="False" 
	GenerateMenuType="top" 
	ListShowPreviewText="True" 
	ListShowDetailText="False" 
	ListShowPreviewPicture="False" 
	PreviewTruncateLen="0" 
	ListShowTitle="True" 
	ListSetTitle="False" 
	ListShowDate="True" 
	ActiveDateFormat="D" 
	HideLinkWhenNoDetail="False" 
	PropertyCode="" 
	DetailShowTitle="False" 
	DetailSetTitle="True" 
	DetailShowDetailPicture="True" 
	DetailShowPreviewPicture="False" 
	DetailShowPreviewText="False" 
	DetailShowDate="True" 
	DetailActiveDateFormat="D" 
	IBlockUrlTitle="Back to the list" 
	DetailPropertyCode="" 
	UseRss="True" 
	RssElementsCount="20" 
	RssDaysCount="" 
	AllowComments="False" 
	CommentsPerPage="5" 
	CommentsForumId="0" 
	CommentAuthorProfileUrlTemplate="" 
	DisplayEmailForGuestComment="True" 
	RequireEmailForGuestComment="True" 
	DisplayCaptchaForGuestComment="True" 
	CommentMaxWordLength="15" 
	EnableSEF="True" 
	SEFFolder="<%$ Options:Bitrix.BankSite:NewsSefFolder %>" 
	ParamSection="section" 
	ParamNews="news" 
	ParamPage="page" 
	ParamShowAll="showall" 
	ParamComment="comment" 
	ParamCommentOperation="act" 
	ParamCommentPage="page" 
	Sef_News="/#SectionId#/item-#ElementId#/" 
	Sef_Rss="/rss/" 
	Sef_Section="/#SectionId#/" 
	Sef_Rss_Section="/rss/#SectionId#/" 
	Sef_Page="/page-#pageId#" 
	Sef_ShowAll="/all" 
	Sef_Section_Page="/#SectionId#/page-#pageId#" 
	Sef_Section_ShowAll="/#SectionId#/all" 
	Sef_Detail_Comment_Read="/#SectionId#/news-#ElementId#/comment-#CommentId#/" 
	Sef_Detail_Comment_Operation="/#SectionId#/news-#ElementId#/comment-#CommentId#/act-#Operation#/" 
	Sef_Detail_Comment_Page="/#SectionId#/news-#ElementId#/page-#PageID#/" 
	EnableAjax="False" 
	DisplaySearchResults="True" 
	PagingAllow="True" 
	PagingMode="direct" 
	PagingTemplate="catalog" 
	PagingShowOne="False" 
	PagingAllowAll="False" 
	PagingTitle="Pages:" 
	PagingPosition="bottom" 
	PagingMaxPages="10" 
	PagingMinRecordsInverse="1" 
	CacheMode="None" 
	CacheDuration="30" 
/> 

 </asp:Content>

