<%@ Page Language="C#" AutoEventWireup="true" Inherits="Bitrix.UI.BXPublicPage, Main"  title="Forums" %>
<asp:Content ID="Content1" ContentPlaceHolderID="bxcontent" runat="server" >

<bx:IncludeComponent 
	id="Forum" 
	runat="server" 
	componentname="bitrix:forum" 
	template=".default" 
	ColorCss="<%$ Options:Bitrix.CommunitySite:ForumColorScheme %>" 
	AvailableForums="" 
	GenerateMenu="False" 
	GenerateMenuType="main" 
	SetPageTitle="True" 
	MaxWordLength="50" 
	ForumListTitle="Forums" 
	GuestEmail="required" 
	GuestCaptcha="True" 
	ForumRulesUrl="" 
	ForumHelpUrl="" 
	EnableSEF="True" 
	SEFFolder="<%$ Options:Bitrix.CommunitySite:ForumSefFolder %>" 
	ForumVariable="forum" 
	TopicVariable="topic" 
	TopicsVariable="topics" 
	PostVariable="post" 
	ActionVariable="act" 
	PageVariable="page" 
	UserVariable="user" 
	NewTopicTemplate="/#i:ForumId#/new/" 
	MoveTopicsTemplate="/move/?topics=#MoveTopicsIds#" 
	TopicListTemplate="/#i:ForumId#/" 
	TopicListPageTemplate="/#i:ForumId#/page-#PageId#/" 
	TopicTemplate="/#i:ForumId#/#i:TopicId#/" 
	TopicPageTemplate="/#i:ForumId#/#i:TopicId#/page-#PageId#/" 
	TopicReplyTemplate="/#i:ForumId#/#i:TopicId#/reply/" 
	TopicMoveTemplate="/#i:ForumId#/#i:TopicId#/move/" 
	TopicEditTemplate="/#i:ForumId#/#i:TopicId#/edit/" 
	PostReadTemplate="/#i:ForumId#/#i:TopicId#/#i:PostId#/##post#PostId#" 
	PostQuoteTemplate="/#i:ForumId#/#i:TopicId#/#i:PostId#/quote/" 
	PostEditTemplate="/#i:ForumId#/#i:TopicId#/#i:PostId#/edit/" 
	UserProfileTemplate="/people/#i:UserId#/" 
	UserProfileEditTemplate="/people/#i:UserId#/edit/" 
	ForumRulesTemplate="/rules/" 
	ForumHelpTemplate="/help/" 
	DisplaySearchResults="True" 
	PagingAllow="True" 
	PagingMode="direct" 
	PagingTemplate="customizable" 
	PagingShowOne="True" 
	PagingRecordsPerPage="25" 
	PagingTitle="Pages:" 
	PagingPosition="both" 
	PagingMaxPages="5" 
	PagingMinRecordsInverse="1" 
	UserProfileUrl="<%$ Options:Bitrix.CommunitySite:UserProfileUrlTemplate %>" 
	UserProfileEditUrl="<%$ Options:Bitrix.CommunitySite:UserProfileEditUrlTemplate %>" 
	RssTopicsAllTemplate="/rss/topics/" 
	RssTopicsFromForumTemplate="/#i:ForumId#/rss/topics/" 
	RssPostsFromTopicTemplate="/#i:ForumId#/#TopicId#/rss/" 
	ShowNavigation="True" 
	ShowMenu="True" 
	EnableRss="True" 
	RssCacheMode="Auto" 
	RssCacheDuration="900" 
	RssItemQuantity="20" 
	RssFeedTtl="60" 
	EnableSearch="True" 
	UserSubscriptionsUrlTemplate="/subscriptions/" 
	UserSubscriptionsPageUrlTemplate="/subscriptions/?page=#PageId#" 
	UserPostsTemplate="/users/#i:UserId#/posts/" 
	UserPostsPageTemplate="/users/#i:UserId#/posts/?page=#PageId#" 
	ActiveTopicsUrlTemplate="/active/" 
	ActiveTopicsPageUrlTemplate="/active/?page=#PageId#" 
	UnAnsweredTopicsUrlTemplate="/unanswered/" 
	UnAnsweredTopicsPageUrlTemplate="/unanswered/?page=#PageId#" 
	SearchUrlTemplate="/search/" 
	SearchPageUrlTemplate="/search/?page=#PageId#" 
	SearchStringVariable="query" 
	DateIntervalVariable="period" 
	ForumsVariable="forums" 
	SortingVariable="sort" 
	GuestMenuTextTemplate="Hello, Guest!" 
	UserMenuTextTemplate="Hello, #UserDisplayName#!" 
	EnableVotingForTopic="True" 
	EnableVotingForPost="True" 
	RolesAuthorizedToVote="User" 
	SortTopicsByVotingTotals="False" 
/>

</asp:Content>
