<%@ Page Language="C#" AutoEventWireup="true" Inherits="Bitrix.UI.BXPublicPage, Main" Title="Career Opportunities" %>

<asp:Content ID="Content1" ContentPlaceHolderID="bxcontent" runat="server" > 

  <bx:IncludeComponent 
	  id="catalogue1" 
	  runat="server" 
	  componentname="bitrix:catalogue" 
	  template="vacancies" 
	  IBlockTypeId="" 
	  IBlockId="<%$ Options:Bitrix.BankSite:VacanciesIblockId,int %>" 
	  AddAdminPanelButtons="False" 
	  SetPageTitle="False" 
	  RootSectionTitle="" 
	  GenerateMenu="False" 
	  GenerateMenuType="top" 
	  AllowComments="False" 
	  CommentsPerPage="5" 
	  CommentsForumId="0" 
	  CommentAuthorProfileUrlTemplate="" 
	  DisplayEmailForGuestComment="True" 
	  RequireEmailForGuestComment="True" 
	  DisplayCaptchaForGuestComment="True" 
	  CommentMaxWordLength="15" 
	  EnableSEF="True" 
	  SEFFolder="<%$ Options:Bitrix.BankSite:VacanciesSefFolder %>" 
	  SectionIdVariable="section_id" 
	  ElementIdVariable="element_id" 
	  PageIdVariable="page" 
	  ShowAllVariable="showall" 
	  CommentVariable="comment" 
	  CommentOperationVariable="act" 
	  CommentPageVariable="page" 
	  ElementDetailTemplate="/item-#ElementId#/" 
	  ElementListTemplate="/#SectionId#/" 
	  CommonListPageTemplate="/page-#pageId#" 
	  CommonListShowAllTemplate="/all" 
	  SectionListPageTemplate="/page-#pageId#" 
	  SectionListShowAllTemplate="/#SectionId#/all" 
	  ElementDetailCommentReadTemplate="/item-#ElementId#/comment-#CommentId#/" 
	  ElementDetailCommentOperationTemplate="/item-#ElementId#/comment-#CommentId#/act-#Operation#/" 
	  ElementDetailCommentPageTemplate="/item-#ElementId#/page-#PageID#/" 
	  EnableAjax="False" 
	  DisplaySearchResults="True" 
	  ListSortBy="ID" 
	  ListSortOrder="Desc" 
	  ShowSubElements="True" 
	  ShowAllElementsOnIndex="True" 
	  ActiveFilter="Active" 
	  ActiveDateFilter="All" 
	  ListProperties="-" 
	  DetailProperties="REQS;RESPS;CONDS" 
	  PropertyKeywords="-" 
	  PropertyDescription="-" 
	  DepthLevel="2" 
	  ShowCounters="False" 
	  IncludeParentSections="True" 
	  ShowTopElements="False" 
	  TopElementCount="6" 
	  TopSortBy="ID" 
	  TopSortOrder="Desc" 
	  TopProperties="-" 
	  PagingAllow="True" 
	  PagingMode="direct" 
	  PagingTemplate="catalog" 
	  PagingShowOne="False" 
	  PagingAllowAll="False" 
	  PagingRecordsPerPage="15" 
	  PagingTitle="Pages" 
	  PagingPosition="bottom" 
	  PagingMaxPages="10" 
	  PagingMinRecordsInverse="1" 
	  CacheMode="None" 
	  CacheDuration="30" 
  /> 

 </asp:Content>

